_infra-eureka:
  deployments:
    eureka:
      replicaCount: 1
      image:
        repository: your-registry/eurekaservice
        tag: "dev-latest"
      env:
        SPRING_PROFILES_ACTIVE: "dev"
